export const modes = [
    {
        id: "standard",
        modeName: "Standaard",
        rows: [
            [
                {"x":0, "y":0, "color":"red", "number":2, "clicked": false, disabled: false },
                {"x":1, "y":0, "color":"red", "number":3, "clicked": false, disabled: false },
                {"x":2, "y":0, "color":"red", "number":4, "clicked": false, disabled: false },   
                {"x":3, "y":0, "color":"red", "number":5, "clicked": false, disabled: false },
                {"x":4, "y":0, "color":"red", "number":6, "clicked": false, disabled: false },
                {"x":5, "y":0, "color":"red", "number":7, "clicked": false, disabled: false },
                {"x":6, "y":0, "color":"red", "number":8, "clicked": false, disabled: false },
                {"x":7, "y":0, "color":"red", "number":9, "clicked": false, disabled: false},
                {"x":8, "y":0, "color":"red", "number":10, "clicked": false, disabled: false },
                {"x":9, "y":0, "color":"red", "number":11, "clicked": false, disabled: false },
                {"x":10, "y":0, "color":"red", "number":12, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":1, "color":"yellow", "number":2, "clicked": false, disabled: false },
                {"x":1, "y":1, "color":"yellow", "number":3, "clicked": false, disabled: false },
                {"x":2, "y":1, "color":"yellow", "number":4, "clicked": false, disabled: false },   
                {"x":3, "y":1, "color":"yellow", "number":5, "clicked": false, disabled: false },
                {"x":4, "y":1, "color":"yellow", "number":6, "clicked": false, disabled: false },
                {"x":5, "y":1, "color":"yellow", "number":7, "clicked": false, disabled: false },
                {"x":6, "y":1, "color":"yellow", "number":8, "clicked": false, disabled: false },
                {"x":7, "y":1, "color":"yellow", "number":9, "clicked": false, disabled: false},
                {"x":8, "y":1, "color":"yellow", "number":10, "clicked": false, disabled: false },
                {"x":9, "y":1, "color":"yellow", "number":11, "clicked": false, disabled: false },
                {"x":10, "y":1, "color":"yellow", "number":12, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":2, "color":"green", "number":12, "clicked": false, disabled: false },
                {"x":1, "y":2, "color":"green", "number":11, "clicked": false, disabled: false },
                {"x":2, "y":2, "color":"green", "number":10, "clicked": false, disabled: false },   
                {"x":3, "y":2, "color":"green", "number":9, "clicked": false, disabled: false },
                {"x":4, "y":2, "color":"green", "number":8, "clicked": false, disabled: false },
                {"x":5, "y":2, "color":"green", "number":7, "clicked": false, disabled: false },
                {"x":6, "y":2, "color":"green", "number":6, "clicked": false, disabled: false },
                {"x":7, "y":2, "color":"green", "number":5, "clicked": false, disabled: false},
                {"x":8, "y":2, "color":"green", "number":4, "clicked": false, disabled: false },
                {"x":9, "y":2, "color":"green", "number":3, "clicked": false, disabled: false },
                {"x":10, "y":2, "color":"green", "number":2, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":3, "color":"blue", "number":12, "clicked": false, disabled: false },
                {"x":1, "y":3, "color":"blue", "number":11, "clicked": false, disabled: false },
                {"x":2, "y":3, "color":"blue", "number":10, "clicked": false, disabled: false },   
                {"x":3, "y":3, "color":"blue", "number":9, "clicked": false, disabled: false },
                {"x":4, "y":3, "color":"blue", "number":8, "clicked": false, disabled: false },
                {"x":5, "y":3, "color":"blue", "number":7, "clicked": false, disabled: false },
                {"x":6, "y":3, "color":"blue", "number":6, "clicked": false, disabled: false },
                {"x":7, "y":3, "color":"blue", "number":5, "clicked": false, disabled: false},
                {"x":8, "y":3, "color":"blue", "number":4, "clicked": false, disabled: false },
                {"x":9, "y":3, "color":"blue", "number":3, "clicked": false, disabled: false },
                {"x":10, "y":3, "color":"blue", "number":2, "clicked": false, disabled: true },
            ],
        ],
        locks: [
            {"row" : 0, "color" : "red", "clicked" : false },
            {"row" : 1, "color" : "yellow", "clicked" : false },
            {"row" : 2, "color" : "green", "clicked" : false },
            {"row" : 3, "color" : "blue", "clicked" : false }
        ]
    },
    {
        id: "mixed1",
        modeName: "Mixed 1",
        rows: [
            [
                {"x":0,  "y":0, "color":"red", "number":10, "clicked": false, disabled: false },
                {"x":1,  "y":0, "color":"red", "number":6,  "clicked": false, disabled: false },
                {"x":2,  "y":0, "color":"red", "number":2,  "clicked": false, disabled: false },   
                {"x":3,  "y":0, "color":"red", "number":8,  "clicked": false, disabled: false },
                {"x":4,  "y":0, "color":"red", "number":3,  "clicked": false, disabled: false },
                {"x":5,  "y":0, "color":"red", "number":4,  "clicked": false, disabled: false },
                {"x":6,  "y":0, "color":"red", "number":12, "clicked": false, disabled: false },
                {"x":7,  "y":0, "color":"red", "number":5,  "clicked": false, disabled: false },
                {"x":8,  "y":0, "color":"red", "number":9,  "clicked": false, disabled: false },
                {"x":9,  "y":0, "color":"red", "number":7,  "clicked": false, disabled: false },
                {"x":10, "y":0, "color":"red", "number":11, "clicked": false, disabled: true  },
            ],
            [
                {"x":0,  "y":1, "color":"yellow", "number":9,  "clicked": false, disabled: false },
                {"x":1,  "y":1, "color":"yellow", "number":12, "clicked": false, disabled: false },
                {"x":2,  "y":1, "color":"yellow", "number":4,  "clicked": false, disabled: false },   
                {"x":3,  "y":1, "color":"yellow", "number":6,  "clicked": false, disabled: false },
                {"x":4,  "y":1, "color":"yellow", "number":7,  "clicked": false, disabled: false },
                {"x":5,  "y":1, "color":"yellow", "number":2,  "clicked": false, disabled: false },
                {"x":6,  "y":1, "color":"yellow", "number":5,  "clicked": false, disabled: false },
                {"x":7,  "y":1, "color":"yellow", "number":8,  "clicked": false, disabled: false },
                {"x":8,  "y":1, "color":"yellow", "number":11, "clicked": false, disabled: false },
                {"x":9,  "y":1, "color":"yellow", "number":3,  "clicked": false, disabled: false },
                {"x":10, "y":1, "color":"yellow", "number":10, "clicked": false, disabled: true  },
            ],
            [
                {"x":0,  "y":2, "color":"green", "number":8,  "clicked": false, disabled: false },
                {"x":1,  "y":2, "color":"green", "number":2,  "clicked": false, disabled: false },
                {"x":2,  "y":2, "color":"green", "number":10, "clicked": false, disabled: false },   
                {"x":3,  "y":2, "color":"green", "number":12, "clicked": false, disabled: false },
                {"x":4,  "y":2, "color":"green", "number":6,  "clicked": false, disabled: false },
                {"x":5,  "y":2, "color":"green", "number":9,  "clicked": false, disabled: false },
                {"x":6,  "y":2, "color":"green", "number":7,  "clicked": false, disabled: false },
                {"x":7,  "y":2, "color":"green", "number":4,  "clicked": false, disabled: false },
                {"x":8,  "y":2, "color":"green", "number":5,  "clicked": false, disabled: false },
                {"x":9,  "y":2, "color":"green", "number":11, "clicked": false, disabled: false },
                {"x":10, "y":2, "color":"green", "number":3,  "clicked": false, disabled: true  },
            ],
            [
                {"x":0,  "y":3, "color":"blue", "number":5,  "clicked": false, disabled: false },
                {"x":1,  "y":3, "color":"blue", "number":7,  "clicked": false, disabled: false },
                {"x":2,  "y":3, "color":"blue", "number":11, "clicked": false, disabled: false },   
                {"x":3,  "y":3, "color":"blue", "number":9,  "clicked": false, disabled: false },
                {"x":4,  "y":3, "color":"blue", "number":12, "clicked": false, disabled: false },
                {"x":5,  "y":3, "color":"blue", "number":3,  "clicked": false, disabled: false },
                {"x":6,  "y":3, "color":"blue", "number":8,  "clicked": false, disabled: false },
                {"x":7,  "y":3, "color":"blue", "number":10, "clicked": false, disabled: false },
                {"x":8,  "y":3, "color":"blue", "number":2,  "clicked": false, disabled: false },
                {"x":9,  "y":3, "color":"blue", "number":6,  "clicked": false, disabled: false },
                {"x":10, "y":3, "color":"blue", "number":4,  "clicked": false, disabled: true  },
            ]
        ],
        locks: [
            {"row" : 0, "color" : "red", "clicked" : false },
            {"row" : 1, "color" : "yellow", "clicked" : false },
            {"row" : 2, "color" : "green", "clicked" : false },
            {"row" : 3, "color" : "blue", "clicked" : false }
        ]
    },
    {
        id: "mixed2",
        modeName: "Mixed 2",
        rows: [
            [
                {"x":0, "y":0, "color":"yellow", "number":2, "clicked": false, disabled: false },
                {"x":1, "y":0, "color":"yellow", "number":3, "clicked": false, disabled: false },
                {"x":2, "y":0, "color":"yellow", "number":4, "clicked": false, disabled: false },   
                {"x":3, "y":0, "color":"blue", "number":5, "clicked": false, disabled: false },
                {"x":4, "y":0, "color":"blue", "number":6, "clicked": false, disabled: false },
                {"x":5, "y":0, "color":"blue", "number":7, "clicked": false, disabled: false },
                {"x":6, "y":0, "color":"green", "number":8, "clicked": false, disabled: false },
                {"x":7, "y":0, "color":"green", "number":9, "clicked": false, disabled: false},
                {"x":8, "y":0, "color":"green", "number":10, "clicked": false, disabled: false },
                {"x":9, "y":0, "color":"red", "number":11, "clicked": false, disabled: false },
                {"x":10, "y":0, "color":"red", "number":12, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":1, "color":"red", "number":2, "clicked": false, disabled: false },
                {"x":1, "y":1, "color":"red", "number":3, "clicked": false, disabled: false },
                {"x":2, "y":1, "color":"green", "number":4, "clicked": false, disabled: false },   
                {"x":3, "y":1, "color":"green", "number":5, "clicked": false, disabled: false },
                {"x":4, "y":1, "color":"green", "number":6, "clicked": false, disabled: false },
                {"x":5, "y":1, "color":"green", "number":7, "clicked": false, disabled: false },
                {"x":6, "y":1, "color":"blue", "number":8, "clicked": false, disabled: false },
                {"x":7, "y":1, "color":"blue", "number":9, "clicked": false, disabled: false},
                {"x":8, "y":1, "color":"yellow", "number":10, "clicked": false, disabled: false },
                {"x":9, "y":1, "color":"yellow", "number":11, "clicked": false, disabled: false },
                {"x":10, "y":1, "color":"yellow", "number":12, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":2, "color":"blue", "number":12, "clicked": false, disabled: false },
                {"x":1, "y":2, "color":"blue", "number":11, "clicked": false, disabled: false },
                {"x":2, "y":2, "color":"blue", "number":10, "clicked": false, disabled: false },   
                {"x":3, "y":2, "color":"yellow", "number":9, "clicked": false, disabled: false },
                {"x":4, "y":2, "color":"yellow", "number":8, "clicked": false, disabled: false },
                {"x":5, "y":2, "color":"yellow", "number":7, "clicked": false, disabled: false },
                {"x":6, "y":2, "color":"red", "number":6, "clicked": false, disabled: false },
                {"x":7, "y":2, "color":"red", "number":5, "clicked": false, disabled: false},
                {"x":8, "y":2, "color":"red", "number":4, "clicked": false, disabled: false },
                {"x":9, "y":2, "color":"green", "number":3, "clicked": false, disabled: false },
                {"x":10, "y":2, "color":"green", "number":2, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":3, "color":"green", "number":12, "clicked": false, disabled: false },
                {"x":1, "y":3, "color":"green", "number":11, "clicked": false, disabled: false },
                {"x":2, "y":3, "color":"red", "number":10, "clicked": false, disabled: false },   
                {"x":3, "y":3, "color":"red", "number":9, "clicked": false, disabled: false },
                {"x":4, "y":3, "color":"red", "number":8, "clicked": false, disabled: false },
                {"x":5, "y":3, "color":"red", "number":7, "clicked": false, disabled: false },
                {"x":6, "y":3, "color":"yellow", "number":6, "clicked": false, disabled: false },
                {"x":7, "y":3, "color":"yellow", "number":5, "clicked": false, disabled: false},
                {"x":8, "y":3, "color":"blue", "number":4, "clicked": false, disabled: false },
                {"x":9, "y":3, "color":"blue", "number":3, "clicked": false, disabled: false },
                {"x":10, "y":3, "color":"blue", "number":2, "clicked": false, disabled: true },
            ],
        ],
        locks: [
            {"row" : 0, "color" : "red", "clicked" : false },
            {"row" : 1, "color" : "yellow", "clicked" : false },
            {"row" : 2, "color" : "green", "clicked" : false },
            {"row" : 3, "color" : "blue", "clicked" : false }
        ]
    },
    {
        id: "connect1a",
        modeName: "Connect 1A",
        rows: [
            [
                {"x":0, "y":0, "color":"red", "number":2, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":0, "color":"red", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":0, "color":"red", "number":4, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":0, "color":"red", "number":5, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":0, "color":"red", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":0, "color":"red", "number":7, "highlight" : true, "clicked": false, disabled: false },
                {"x":6, "y":0, "color":"red", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":0, "color":"red", "number":9, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":0, "color":"red", "number":10, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":0, "color":"red", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":0, "color":"red", "number":12, "highlight" : false, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":1, "color":"yellow", "number":2, "highlight" : true, "clicked": false, disabled: false },
                {"x":1, "y":1, "color":"yellow", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":1, "color":"yellow", "number":4, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":1, "color":"yellow", "number":5, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":1, "color":"yellow", "number":6, "highlight" : true, "clicked": false, disabled: false },
                {"x":5, "y":1, "color":"yellow", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":1, "color":"yellow", "number":8, "highlight" : true, "clicked": false, disabled: false },
                {"x":7, "y":1, "color":"yellow", "number":9, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":1, "color":"yellow", "number":10, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":1, "color":"yellow", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":1, "color":"yellow", "number":12, "highlight" : true, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":2, "color":"green", "number":12, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":2, "color":"green", "number":11, "highlight" : true, "clicked": false, disabled: false },
                {"x":2, "y":2, "color":"green", "number":10, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":2, "color":"green", "number":9, "highlight" : true, "clicked": false, disabled: false },
                {"x":4, "y":2, "color":"green", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":2, "color":"green", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":2, "color":"green", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":2, "color":"green", "number":5, "highlight" : true, "clicked": false, disabled: false},
                {"x":8, "y":2, "color":"green", "number":4, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":2, "color":"green", "number":3, "highlight" : true, "clicked": false, disabled: false },
                {"x":10, "y":2, "color":"green", "number":2, "highlight" : false, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":3, "color":"blue", "number":12, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":3, "color":"blue", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":3, "color":"blue", "number":10, "highlight" : true, "clicked": false, disabled: false },   
                {"x":3, "y":3, "color":"blue", "number":9, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":3, "color":"blue", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":3, "color":"blue", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":3, "color":"blue", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":3, "color":"blue", "number":5, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":3, "color":"blue", "number":4, "highlight" : true, "clicked": false, disabled: false },
                {"x":9, "y":3, "color":"blue", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":3, "color":"blue", "number":2, "highlight" : false, "clicked": false, disabled: true },
            ],
        ],
        locks: [
            {"row" : 0, "color" : "red", "clicked" : false },
            {"row" : 1, "color" : "yellow", "clicked" : false },
            {"row" : 2, "color" : "green", "clicked" : false },
            {"row" : 3, "color" : "blue", "clicked" : false },
            {"row" : undefined, "color" : "highlight", "clicked" : false }
        ]
    },
    {
        id: "connect1b",
        modeName: "Connect 1B",
        rows: [
            [
                {"x":0, "y":0, "color":"red", "number":2, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":0, "color":"red", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":0, "color":"red", "number":4, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":0, "color":"red", "number":5, "highlight" : true, "clicked": false, disabled: false },
                {"x":4, "y":0, "color":"red", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":0, "color":"red", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":0, "color":"red", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":0, "color":"red", "number":9, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":0, "color":"red", "number":10, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":0, "color":"red", "number":11, "highlight" : true, "clicked": false, disabled: false },
                {"x":10, "y":0, "color":"red", "number":12, "highlight" : false, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":1, "color":"yellow", "number":2, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":1, "color":"yellow", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":1, "color":"yellow", "number":4, "highlight" : true, "clicked": false, disabled: false },   
                {"x":3, "y":1, "color":"yellow", "number":5, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":1, "color":"yellow", "number":6, "highlight" : true, "clicked": false, disabled: false },
                {"x":5, "y":1, "color":"yellow", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":1, "color":"yellow", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":1, "color":"yellow", "number":9, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":1, "color":"yellow", "number":10, "highlight" : true, "clicked": false, disabled: false },
                {"x":9, "y":1, "color":"yellow", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":1, "color":"yellow", "number":12, "highlight" : true, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":2, "color":"green", "number":12, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":2, "color":"green", "number":11, "highlight" : true, "clicked": false, disabled: false },
                {"x":2, "y":2, "color":"green", "number":10, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":2, "color":"green", "number":9, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":2, "color":"green", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":2, "color":"green", "number":7, "highlight" : true, "clicked": false, disabled: false },
                {"x":6, "y":2, "color":"green", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":2, "color":"green", "number":5, "highlight" : true, "clicked": false, disabled: false},
                {"x":8, "y":2, "color":"green", "number":4, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":2, "color":"green", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":2, "color":"green", "number":2, "highlight" : false, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":3, "color":"blue", "number":12, "highlight" : true, "clicked": false, disabled: false },
                {"x":1, "y":3, "color":"blue", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":3, "color":"blue", "number":10, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":3, "color":"blue", "number":9, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":3, "color":"blue", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":3, "color":"blue", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":3, "color":"blue", "number":6, "highlight" : true, "clicked": false, disabled: false },
                {"x":7, "y":3, "color":"blue", "number":5, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":3, "color":"blue", "number":4, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":3, "color":"blue", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":3, "color":"blue", "number":2, "highlight" : false, "clicked": false, disabled: true },
            ],
        ],
        locks: [
            {"row" : 0, "color" : "red", "clicked" : false },
            {"row" : 1, "color" : "yellow", "clicked" : false },
            {"row" : 2, "color" : "green", "clicked" : false },
            {"row" : 3, "color" : "blue", "clicked" : false }
        ]
    },
    {
        id: "connect1c",
        modeName: "Connect 1C",
        rows: [
            [
                {"x":0, "y":0, "color":"red", "number":2, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":0, "color":"red", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":0, "color":"red", "number":4, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":0, "color":"red", "number":5, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":0, "color":"red", "number":6, "highlight" : true, "clicked": false, disabled: false },
                {"x":5, "y":0, "color":"red", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":0, "color":"red", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":0, "color":"red", "number":9, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":0, "color":"red", "number":10, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":0, "color":"red", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":0, "color":"red", "number":12, "highlight" : true, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":1, "color":"yellow", "number":2, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":1, "color":"yellow", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":1, "color":"yellow", "number":4, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":1, "color":"yellow", "number":5, "highlight" : true, "clicked": false, disabled: false },
                {"x":4, "y":1, "color":"yellow", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":1, "color":"yellow", "number":7, "highlight" : true, "clicked": false, disabled: false },
                {"x":6, "y":1, "color":"yellow", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":1, "color":"yellow", "number":9, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":1, "color":"yellow", "number":10, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":1, "color":"yellow", "number":11, "highlight" : true, "clicked": false, disabled: false },
                {"x":10, "y":1, "color":"yellow", "number":12, "highlight" : false, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":2, "color":"green", "number":12, "highlight" : true, "clicked": false, disabled: false },
                {"x":1, "y":2, "color":"green", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":2, "color":"green", "number":10, "highlight" : true, "clicked": false, disabled: false },   
                {"x":3, "y":2, "color":"green", "number":9, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":2, "color":"green", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":2, "color":"green", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":2, "color":"green", "number":6, "highlight" : true, "clicked": false, disabled: false },
                {"x":7, "y":2, "color":"green", "number":5, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":2, "color":"green", "number":4, "highlight" : true, "clicked": false, disabled: false },
                {"x":9, "y":2, "color":"green", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":2, "color":"green", "number":2, "highlight" : false, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":3, "color":"blue", "number":12, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":3, "color":"blue", "number":11, "highlight" : true, "clicked": false, disabled: false },
                {"x":2, "y":3, "color":"blue", "number":10, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":3, "color":"blue", "number":9, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":3, "color":"blue", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":3, "color":"blue", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":3, "color":"blue", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":3, "color":"blue", "number":5, "highlight" : true, "clicked": false, disabled: false},
                {"x":8, "y":3, "color":"blue", "number":4, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":3, "color":"blue", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":3, "color":"blue", "number":2, "highlight" : false, "clicked": false, disabled: true },
            ],
        ],
        locks: [
            {"row" : 0, "color" : "red", "clicked" : false },
            {"row" : 1, "color" : "yellow", "clicked" : false },
            {"row" : 2, "color" : "green", "clicked" : false },
            {"row" : 3, "color" : "blue", "clicked" : false }
        ]
    },
    {
        id: "connect1d",
        modeName: "Connect 1D",
        rows: [
            [
                {"x":0, "y":0, "color":"red", "number":2, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":0, "color":"red", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":0, "color":"red", "number":4, "highlight" : true, "clicked": false, disabled: false },   
                {"x":3, "y":0, "color":"red", "number":5, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":0, "color":"red", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":0, "color":"red", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":0, "color":"red", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":0, "color":"red", "number":9, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":0, "color":"red", "number":10, "highlight" : true, "clicked": false, disabled: false },
                {"x":9, "y":0, "color":"red", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":0, "color":"red", "number":12, "highlight" : false, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":1, "color":"yellow", "number":2, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":1, "color":"yellow", "number":3, "highlight" : true, "clicked": false, disabled: false },
                {"x":2, "y":1, "color":"yellow", "number":4, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":1, "color":"yellow", "number":5, "highlight" : true, "clicked": false, disabled: false },
                {"x":4, "y":1, "color":"yellow", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":1, "color":"yellow", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":1, "color":"yellow", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":1, "color":"yellow", "number":9, "highlight" : true, "clicked": false, disabled: false},
                {"x":8, "y":1, "color":"yellow", "number":10, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":1, "color":"yellow", "number":11, "highlight" : true, "clicked": false, disabled: false },
                {"x":10, "y":1, "color":"yellow", "number":12, "highlight" : false, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":2, "color":"green", "number":12, "highlight" : true, "clicked": false, disabled: false },
                {"x":1, "y":2, "color":"green", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":2, "color":"green", "number":10, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":2, "color":"green", "number":9, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":2, "color":"green", "number":8, "highlight" : true, "clicked": false, disabled: false },
                {"x":5, "y":2, "color":"green", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":2, "color":"green", "number":6, "highlight" : true, "clicked": false, disabled: false },
                {"x":7, "y":2, "color":"green", "number":5, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":2, "color":"green", "number":4, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":2, "color":"green", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":2, "color":"green", "number":2, "highlight" : true, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":3, "color":"blue", "number":12, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":3, "color":"blue", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":3, "color":"blue", "number":10, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":3, "color":"blue", "number":9, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":3, "color":"blue", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":3, "color":"blue", "number":7, "highlight" : true, "clicked": false, disabled: false },
                {"x":6, "y":3, "color":"blue", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":3, "color":"blue", "number":5, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":3, "color":"blue", "number":4, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":3, "color":"blue", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":3, "color":"blue", "number":2, "highlight" : false, "clicked": false, disabled: true },
            ],
        ],
        locks: [
            {"row" : 0, "color" : "red", "clicked" : false },
            {"row" : 1, "color" : "yellow", "clicked" : false },
            {"row" : 2, "color" : "green", "clicked" : false },
            {"row" : 3, "color" : "blue", "clicked" : false }
        ]
    },
    {
        id: "connect1e",
        modeName: "Connect 1E",
        rows: [
            [
                {"x":0, "y":0, "color":"red", "number":2, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":0, "color":"red", "number":3, "highlight" : true, "clicked": false, disabled: false },
                {"x":2, "y":0, "color":"red", "number":4, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":0, "color":"red", "number":5, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":0, "color":"red", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":0, "color":"red", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":0, "color":"red", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":0, "color":"red", "number":9, "highlight" : true, "clicked": false, disabled: false},
                {"x":8, "y":0, "color":"red", "number":10, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":0, "color":"red", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":0, "color":"red", "number":12, "highlight" : false, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":1, "color":"yellow", "number":2, "highlight" : true, "clicked": false, disabled: false },
                {"x":1, "y":1, "color":"yellow", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":1, "color":"yellow", "number":4, "highlight" : true, "clicked": false, disabled: false },   
                {"x":3, "y":1, "color":"yellow", "number":5, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":1, "color":"yellow", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":1, "color":"yellow", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":1, "color":"yellow", "number":8, "highlight" : true, "clicked": false, disabled: false },
                {"x":7, "y":1, "color":"yellow", "number":9, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":1, "color":"yellow", "number":10, "highlight" : true, "clicked": false, disabled: false },
                {"x":9, "y":1, "color":"yellow", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":1, "color":"yellow", "number":12, "highlight" : false, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":2, "color":"green", "number":12, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":2, "color":"green", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":2, "color":"green", "number":10, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":2, "color":"green", "number":9, "highlight" : true, "clicked": false, disabled: false },
                {"x":4, "y":2, "color":"green", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":2, "color":"green", "number":7, "highlight" : true, "clicked": false, disabled: false },
                {"x":6, "y":2, "color":"green", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":2, "color":"green", "number":5, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":2, "color":"green", "number":4, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":2, "color":"green", "number":3, "highlight" : true, "clicked": false, disabled: false },
                {"x":10, "y":2, "color":"green", "number":2, "highlight" : false, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":3, "color":"blue", "number":12, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":3, "color":"blue", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":3, "color":"blue", "number":10, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":3, "color":"blue", "number":9, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":3, "color":"blue", "number":8, "highlight" : true, "clicked": false, disabled: false },
                {"x":5, "y":3, "color":"blue", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":3, "color":"blue", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":3, "color":"blue", "number":5, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":3, "color":"blue", "number":4, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":3, "color":"blue", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":3, "color":"blue", "number":2, "highlight" : true, "clicked": false, disabled: true },
            ],
        ],
        locks: [
            {"row" : 0, "color" : "red", "clicked" : false },
            {"row" : 1, "color" : "yellow", "clicked" : false },
            {"row" : 2, "color" : "green", "clicked" : false },
            {"row" : 3, "color" : "blue", "clicked" : false }
        ]
    },
    {
        id: "connect1f",
        modeName: "Connect 1F",
        rows: [
            [
                {"x":0, "y":0, "color":"red", "number":2, "highlight" : true, "clicked": false, disabled: false },
                {"x":1, "y":0, "color":"red", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":0, "color":"red", "number":4, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":0, "color":"red", "number":5, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":0, "color":"red", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":0, "color":"red", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":0, "color":"red", "number":8, "highlight" : true, "clicked": false, disabled: false },
                {"x":7, "y":0, "color":"red", "number":9, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":0, "color":"red", "number":10, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":0, "color":"red", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":0, "color":"red", "number":12, "highlight" : false, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":1, "color":"yellow", "number":2, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":1, "color":"yellow", "number":3, "highlight" : true, "clicked": false, disabled: false },
                {"x":2, "y":1, "color":"yellow", "number":4, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":1, "color":"yellow", "number":5, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":1, "color":"yellow", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":1, "color":"yellow", "number":7, "highlight" : true, "clicked": false, disabled: false },
                {"x":6, "y":1, "color":"yellow", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":1, "color":"yellow", "number":9, "highlight" : true, "clicked": false, disabled: false},
                {"x":8, "y":1, "color":"yellow", "number":10, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":1, "color":"yellow", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":1, "color":"yellow", "number":12, "highlight" : false, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":2, "color":"green", "number":12, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":2, "color":"green", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":2, "color":"green", "number":10, "highlight" : true, "clicked": false, disabled: false },   
                {"x":3, "y":2, "color":"green", "number":9, "highlight" : false, "clicked": false, disabled: false },
                {"x":4, "y":2, "color":"green", "number":8, "highlight" : true, "clicked": false, disabled: false },
                {"x":5, "y":2, "color":"green", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":2, "color":"green", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":2, "color":"green", "number":5, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":2, "color":"green", "number":4, "highlight" : true, "clicked": false, disabled: false },
                {"x":9, "y":2, "color":"green", "number":3, "highlight" : false, "clicked": false, disabled: false },
                {"x":10, "y":2, "color":"green", "number":2, "highlight" : true, "clicked": false, disabled: true },
            ],
            [
                {"x":0, "y":3, "color":"blue", "number":12, "highlight" : false, "clicked": false, disabled: false },
                {"x":1, "y":3, "color":"blue", "number":11, "highlight" : false, "clicked": false, disabled: false },
                {"x":2, "y":3, "color":"blue", "number":10, "highlight" : false, "clicked": false, disabled: false },   
                {"x":3, "y":3, "color":"blue", "number":9, "highlight" : true, "clicked": false, disabled: false },
                {"x":4, "y":3, "color":"blue", "number":8, "highlight" : false, "clicked": false, disabled: false },
                {"x":5, "y":3, "color":"blue", "number":7, "highlight" : false, "clicked": false, disabled: false },
                {"x":6, "y":3, "color":"blue", "number":6, "highlight" : false, "clicked": false, disabled: false },
                {"x":7, "y":3, "color":"blue", "number":5, "highlight" : false, "clicked": false, disabled: false},
                {"x":8, "y":3, "color":"blue", "number":4, "highlight" : false, "clicked": false, disabled: false },
                {"x":9, "y":3, "color":"blue", "number":3, "highlight" : true, "clicked": false, disabled: false },
                {"x":10, "y":3, "color":"blue", "number":2, "highlight" : false, "clicked": false, disabled: true },
            ],
        ],
        locks: [
            {"row" : 0, "color" : "red", "clicked" : false },
            {"row" : 1, "color" : "yellow", "clicked" : false },
            {"row" : 2, "color" : "green", "clicked" : false },
            {"row" : 3, "color" : "blue", "clicked" : false }
        ]
    }
];